/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */
var gradle_version = "6.2"
var kotlin_version = "1.3.61"
var ktor_version = "1.3.0"


buildscript {

    repositories {
        mavenCentral()
        maven { url = uri("https://kotlin.bintray.com/ktor") }
    }

    dependencies {
        classpath(kotlin("gradle-plugin", version = "1.3.61"))
        kotlin("stdlib-jdk8")
    }
}


plugins {
    kotlin("jvm") version "1.3.61"
    id("java-library")
    id("org.jetbrains.gradle.plugin.idea-ext") version "0.7"
    java
}



allprojects {

    group = "io.alexheld.mockserver"
    version = "1.0.0-PRE"

    repositories {
        gradlePluginPortal()
        mavenCentral()
        jcenter()
        maven { url = uri("https://kotlin.bintray.com/ktor") }
    }


    /**
     * Configures "wrapper" task to use specific Gradle version and distribution type.
     */
    tasks.withType<Wrapper>().configureEach {
        gradleVersion = gradle_version
        distributionType = Wrapper.DistributionType.BIN
    }


    subprojects.forEach { a: Project? ->
        a!!.pluginManager.apply("org.jetbrains.gradle.plugin.idea-ext")
    }

    tasks.withType<JavaCompile>() {
        sourceCompatibility = JavaVersion.VERSION_1_8.toString()
        targetCompatibility = JavaVersion.VERSION_1_8.toString()
    }

    tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile>().all {
        sourceCompatibility = JavaVersion.VERSION_1_8.toString()
        targetCompatibility = JavaVersion.VERSION_1_8.toString()
        kotlinOptions.jvmTarget = "1.8"
    }


}


dependencies {

//    kotlin("stdlib")

    compile("io.ktor:ktor-server-netty:$ktor_version")
    compile("io.ktor:ktor-server-core:$ktor_version")
    compile("ch.qos.logback:logback-classic:1.2.3")
    testCompile(group = "junit", name = "junit", version = "4.12")
    kotlin("stdlib-jdk8")

    compile("ch.qos.logback:logback-classic:1.2.3")
// Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

// Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

// Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")
}
