/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.alexheld.mockserver

import java.util.logging.*
import kotlin.test.*

class AppTest {
    @Test fun testAppHasAGreeting() {
        val classUnderTest = io.alexheld.mockserver.main(emptyArray())
         Logger.getAnonymousLogger().warning("app should have a greeting")
    }
}
