/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.alexheld.mockserver

import io.ktor.application.*
import io.ktor.routing.*
import io.ktor.server.engine.*
import io.ktor.server.netty.*


fun main(args: Array<String>) {

    val server: NettyApplicationEngine = embeddedServer(Netty, 8080){
       routing {
           get("/hello"){
               call.respondWith("sfsdf")
           }
           get
       }
    }


    server.start(wait = true)
}
